n = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('Ele é Númerico?', n.isnumeric())
print('Ele é Alpha?', n.isalpha())
print('Ele é Alpha númerico?', n.isalnum())
print('Ele é Maiusculo??', n.isupper())
print('Ele é Minusculo?', n.islower())
print('Ele é Decimal?', n.isdecimal())
print('Ele é Printavél?', n.isprintable())
